### ISSUE TITLE
créer une vue stagiaire

### ISSUE THREAD

**Issue by michel-plasse** [michel-plasse/SIOMassy2018#1]
Un stagiaire est une personne (ou membre) qui a une candidature d'état "inscrit" dans une session de formation.
La vue comprend les informations de la personne + le id_session voire plus

**Comment by PickleYo** [comment]
<pre>
CREATE VIEW stagiaire AS
	SELECT p.*, sf.*
	FROM 
		personne p
			INNER JOIN
		candidature c ON p.id_personne = c.id_personne
			INNER JOIN
		session_formation sf ON c.id_session_formation = sf.id_session_formation
	WHERE 
		c.id_etat_candidature = 6;
<pre>
